name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: ".x86_64"
            platform: "Linux64"
          - name: ".exe"
            platform: "Win64"
          - name: ".zip"
            platform: "Mac"

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: build
        uses: josephbmanley/build-godot-action@v1.4.1
        with:
          name: fmp2.${{ matrix.extension }}
          preset: ${{ matrix.platform }}
          debugMode: "false"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}